Controllers/AdminUrunController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using on_e_commerce.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.UI.Services;

namespace on_e_commerce.Controllers
{
    [Authorize(Roles = "Admin, Manager, Editor")]
    public class AdminUrunController : Controller
    {
        private readonly dbEticaretContext _context;

        public AdminUrunController(dbEticaretContext context)
        {
            _context = context;
        }

        // GET: AdminUrun
        public async Task<IActionResult> Index()
        {
            var dbEticaretContext = _context.TblUruns.Include(t => t.Kategori);
            return View(await dbEticaretContext.ToListAsync());
        }

        // GET: AdminUrun/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUrun = await _context.TblUruns
                .Include(t => t.Kategori)
                .FirstOrDefaultAsync(m => m.UrunId == id);
            if (tblUrun == null)
            {
                return NotFound();
            }

            return View(tblUrun);
        }

        // GET: AdminUrun/Create
        public IActionResult Create()
        {
            ViewData["KategoriId"] = new SelectList(_context.TblKategoris, "KategoriId", "KategoriAdi");
            return View();
        }

        // POST: AdminUrun/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UrunId,UrunAdi,KategoriId,IsActive,IsDelete,OlusturulmaTarihi,DegistirilmeTarihi,Fiyat,Acıklama,UrunResim,OneCıkan,Miktar,Agırlık")] TblUrun tblUrun, string agirliktürü, IFormFile gorsel)
        {
            if (ModelState.IsValid)
            {
                if (gorsel!=null)
                {
                    string imageExtension = Path.GetExtension(gorsel.FileName);
                    string imageName = Guid.NewGuid() + imageExtension;
                    tblUrun.UrunResim = "wwwroot/Uploads/UrunGorsel/" + imageName;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/Uploads/UrunGorsel/{imageName}");
                    using var stream = new FileStream(path, FileMode.Create);
                    await gorsel.CopyToAsync(stream);

                    tblUrun.OlusturulmaTarihi = DateTime.Now;
                    tblUrun.Agırlık = tblUrun.Agırlık+" "+ agirliktürü;
                    _context.Add(tblUrun);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.HataMesaji = "Görsel alanı boş bırakılamaz.";
                }
            }
            ViewData["KategoriId"] = new SelectList(_context.TblKategoris, "KategoriId", "KategoriAdi", tblUrun.KategoriId);
            return View(tblUrun);
        }

        // GET: AdminUrun/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUrun = await _context.TblUruns.FindAsync(id);
            if (tblUrun == null)
            {
                return NotFound();
            }
            ViewData["KategoriId"] = new SelectList(_context.TblKategoris, "KategoriId", "KategoriAdi", tblUrun.KategoriId);
            return View(tblUrun);
        }

        // POST: AdminUrun/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UrunId,UrunAdi,KategoriId,IsActive,IsDelete,OlusturulmaTarihi,DegistirilmeTarihi,Fiyat,Acıklama,UrunResim,OneCıkan,Miktar,Agırlık")] TblUrun tblUrun,IFormFile gorsel)
        {
            if (id != tblUrun.UrunId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var urun = _context.TblUruns.Where(x => x.KategoriId == id).SingleOrDefault();
                    if (gorsel!=null)
                    {
                        var currenturun = Path.Combine(Directory.GetCurrentDirectory(),urun.UrunResim );
                        if (System.IO.File.Exists(currenturun))
                        {
                            System.IO.File.Delete(currenturun);
                        }
                        string imageExtension = Path.GetExtension(gorsel.FileName);
                        string imageName = Guid.NewGuid() + imageExtension;
                        tblUrun.UrunResim = "wwwroot/Uploads/UrunGorsel/" + imageName;
                        string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/Uploads/UrunGorsel/{imageName}");
                        using var stream = new FileStream(path, FileMode.Create);
                        await gorsel.CopyToAsync(stream);

                        tblUrun.DegistirilmeTarihi = DateTime.Now;
                        _context.Update(tblUrun);
                        await _context.SaveChangesAsync();
                    }
                    else
                    {
                        ViewBag.HataMesaji = "Görsel alanı boş bırakılamaz.";
                    }

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TblUrunExists(tblUrun.UrunId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["KategoriId"] = new SelectList(_context.TblKategoris, "KategoriId", "KategoriAdi", tblUrun.KategoriId);
            return View(tblUrun);
        }

        // GET: AdminUrun/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblUrun = await _context.TblUruns
                .Include(t => t.Kategori)
                .FirstOrDefaultAsync(m => m.UrunId == id);
            if (tblUrun == null)
            {
                return NotFound();
            }

            return View(tblUrun);
        }

        // POST: AdminUrun/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblUrun = await _context.TblUruns.FindAsync(id);
            var currenturun = Path.Combine(Directory.GetCurrentDirectory(), tblUrun.UrunResim);
            if (System.IO.File.Exists(currenturun))
            {
                System.IO.File.Delete(currenturun);
            }

            _context.TblUruns.Remove(tblUrun);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblUrunExists(int id)
        {
            return _context.TblUruns.Any(e => e.UrunId == id);
        }
    }
}

Views/AdminUrun/Create.cshtml
@model on_e_commerce.Models.TblUrun



@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/admin/js/dataTables.bootstrap4.min.js"></script>

@using (Html.BeginForm("Create", "AdminUrun", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card shadow">
        <div class="card-body">
            <div class="form-horizontal">
                <h4 style="margin-left:10px;font-family:'Century Gothic';">Ürün Oluştur</h4>
                <hr />
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Adı</label>
                    <div class="col-md-8">

                        @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Açıklaması</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Acıklama, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Acıklama, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Kategorisi</label>
                    <div class="col-md-8">
                        @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control select2 select2-container select2-container--default select2-container--below" })
                        @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Resmi</label>
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input type="file" required name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
                            @Html.ValidationMessageFor(model => model.UrunResim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Fiyatı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Miktarı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Ağırlığı</label>
                    <div class="row col-md-10">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Agırlık, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Agırlık, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            <select class="select2 select2-container select2-container--default form-control " name="agirliktürü">
                                <option value="kg">kg</option>
                                <option value="gr">gr</option>
                                <option value="ml">ml</option>
                                <option value="lt">lt</option>
                            </select>
                        </div>
                    </div>
                </div>


            </div>
            <div class="form-group">
                <div class="col-auto">
                    <a href="/AdminUrun/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-filter fe-12 mr-2"></span>Kaydet</button>
                </div>

            </div>
        </div>
    </div>
}











Views/AdminUrun/Delete.cshtml
@model on_e_commerce.Models.TblUrun



@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <h3>" @Model.UrunAdi " ürününü silmek istiyor musun?</h3>
    <hr>
    <div class="card shadow">
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UrunAdi)
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4">Ürün Resmi</label>
                    <div class="col-md-8">
                        <div class="avatar avatar-md">
                            <img src="@Model.UrunResim" alt="..." class="avatar-img rounded-circle">
                            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.KategoriId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Oluşturulma Tarihi</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.OlusturulmaTarihi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.OlusturulmaTarihi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Değiştirilme Tarihi</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.DegistirilmeTarihi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.DegistirilmeTarihi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Fiyat</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Açıklama</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Acıklama, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.Acıklama, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Miktar</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Ağırlık</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Agırlık, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.Agırlık, "", new { @class = "text-danger" })
                    </div>
                </div>


            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <a href="/AdminUrun/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-trash fe-12 mr-2"></span>Sil</button>
                </div>
            </div>
        </div>
    </div>
}

Views/AdminUrun/Details.cshtml
@model on_e_commerce.Models.TblUrun



@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h3>" @Model.UrunAdi " Ürünü</h3>
<hr>
<div class="card shadow">
    <div class="card-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UrunAdi)
        <div class="form-horizontal">
            <div class="form-group">
                <label class="control-label col-md-2">Ürün Adı</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-4">Ürün Resmi</label>
                <div class="col-md-8">
                    <div class="avatar avatar-md">
                        <img src="@Model.UrunResim" alt="..." class="avatar-img rounded-circle">
                        @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Kategori Adı</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.KategoriId, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Oluşturulma Tarihi</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.OlusturulmaTarihi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.OlusturulmaTarihi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Değiştirilme Tarihi</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.DegistirilmeTarihi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.DegistirilmeTarihi, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Ürün Fiyat</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Ürün Açıklama</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Acıklama, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Acıklama, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Ürün Miktar</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <label class="control-label col-md-2">Ürün Ağırlık</label>
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Agırlık, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    @Html.ValidationMessageFor(model => model.Agırlık, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>
        <div class="form-group">
            <div class="col-md-4">
                <a href="/AdminUrun/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
            </div>
        </div>
    </div>
</div>

Views/AdminUrun/Edit.cshtml
@model on_e_commerce.Models.TblUrun



@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("Edit", "AdminUrun", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h4> " @Model.UrunAdi " Ürününü Düzenle</h4>
    <hr />
    <div class="card shadow">
        <div class="card-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.UrunAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Açıklaması</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Acıklama, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Acıklama, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Adı</label>
                    <div class="col-md-8">
                        @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control select2 select2-container select2-container--default select2-container--below" })
                        @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4">Mevcut Ürün Resmi</label>
                    <div class="col-md-8">
                        <div class="avatar avatar-md">
                            <img src="@Model.UrunResim" alt="@Model.UrunAdi" class="avatar-img rounded-circle">
                            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Resmi</label>
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input type="file" name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
                            @Html.ValidationMessageFor(model => model.UrunResim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Fiyatı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Miktarı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Miktar, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.Miktar, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-2">Ürün Ağırlığı</label>

                    <div class="row col-md-10">
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Agırlık, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                            @Html.ValidationMessageFor(model => model.Agırlık, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-2">
                            <select class="select2 select2-container select2-container--default form-control " name="agirliktürü">
                                <option value="kg">kg</option>
                                <option value="gr">gr</option>
                                <option value="ml">ml</option>
                                <option value="lt">lt</option>
                            </select>
                        </div>
                    </div>

                </div>
            </div>



            <div class="form-group">
                <div class="col-md-4">
                    <a href="/AdminUrun/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-edit-3 fe-12 mr-2"></span>Kaydet</button>
                </div>
            </div>
        </div>
    </div>
}







