Controllers/AdminKategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using on_e_commerce.Models;
using System.IO;
using System.Web;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity.UI.Services;


namespace on_e_commerce.Controllers
{
    [Authorize(Roles = "Admin, Manager")]
    public class AdminKategoriController : Controller
    {
        private readonly dbEticaretContext _context;

        public AdminKategoriController(dbEticaretContext context)
        {
            _context = context;
        }

        // GET: AdminKategori
        public async Task<IActionResult> Index()
        {
            return View(await _context.TblKategoris.ToListAsync());
        }

        // GET: AdminKategori/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblKategori = await _context.TblKategoris
                .FirstOrDefaultAsync(m => m.KategoriId == id);
            if (tblKategori == null)
            {
                return NotFound();
            }

            return View(tblKategori);
        }

        // GET: AdminKategori/Create
        public IActionResult Create()
        {
            return View();
        }

      
        // POST: AdminKategori/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("KategoriId,KategoriAdi")] TblKategori tblKategori, IFormFile gorsel)
        {
            if (ModelState.IsValid)
            {
                var uniqkategoriadi = _context.TblKategoris.Where(k => k.KategoriAdi == tblKategori.KategoriAdi).SingleOrDefault() ;
                if (uniqkategoriadi==null)
                {
                    if (gorsel!=null)
                    {
                        string imageExtension = Path.GetExtension(gorsel.FileName);
                        string imageName = Guid.NewGuid()+imageExtension;
                        tblKategori.KategoriResim = "wwwroot/Uploads/KategoriGorsel/" + imageName;
                        string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/Uploads/KategoriGorsel/{imageName}");
                        using var stream = new FileStream(path,FileMode.Create);
                        await gorsel.CopyToAsync(stream);
                        _context.Add(tblKategori);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {

                        TempData["kategorisonuc"] = "Görsel alanı boş bırakılamaz.";
                    }
                }
                else
                {

                    TempData["kategorisonuc"] = "Böyle bir kategori zaten oluşturulmuş.";
                }


               
            }
            return View(tblKategori);
        }

        // GET: AdminKategori/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblKategori = await _context.TblKategoris.FindAsync(id);
            if (tblKategori == null)
            {
                return NotFound();
            }
            return View(tblKategori);
        }

        // POST: AdminKategori/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("KategoriId,KategoriAdi,IsActive,IsDelete,KategoriResim")] TblKategori tblKategori, IFormFile gorsel)
        {
            if (id != tblKategori.KategoriId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var kategori = _context.TblKategoris.Where(x=>x.KategoriId==id).SingleOrDefault();
                if (gorsel!=null)
                {

                    var currentpath = Path.Combine(Directory.GetCurrentDirectory(), kategori.KategoriResim);

                    if (System.IO.File.Exists(currentpath))
                    {
                        System.IO.File.Delete(currentpath);
                    }
                    string imageExtension = Path.GetExtension(gorsel.FileName);
                    string imageName = Guid.NewGuid() + imageExtension;
                    tblKategori.KategoriResim = "wwwroot/Uploads/KategoriGorsel/" + imageName;
                    string path = Path.Combine(Directory.GetCurrentDirectory(), $"wwwroot/Uploads/KategoriGorsel/{imageName}");
                    using var stream = new FileStream(path, FileMode.Create);
                    await gorsel.CopyToAsync(stream);
                    _context.Add(tblKategori);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {

                    TempData["kategorisonuc"] = "Görsel alanı boş bırakılamaz.";
                }


            }
            return View(tblKategori);
        }

        // GET: AdminKategori/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblKategori = await _context.TblKategoris
                .FirstOrDefaultAsync(m => m.KategoriId == id);
            if (tblKategori == null)
            {
                return NotFound();
            }

            return View(tblKategori);
        }

        // POST: AdminKategori/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblKategori = await _context.TblKategoris.FindAsync(id);
            var currentpath = Path.Combine(Directory.GetCurrentDirectory(), tblKategori.KategoriResim);
            if (System.IO.File.Exists(currentpath))
            {
                System.IO.File.Delete(currentpath);
            }
            _context.TblKategoris.Remove(tblKategori);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TblKategoriExists(int id)
        {
            return _context.TblKategoris.Any(e => e.KategoriId == id);
        }
    }
}

Views/AdminKategori/Create.cshtml
@model on_e_commerce.Models.TblKategori;

@{
    /**/

    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Create", "AdminKategori", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="card shadow">
        <div class="card-body">
            <div class="form-horizontal">
                <h4 style="margin-left:10px;font-family:'Century Gothic';">Kategori Oluştur</h4>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Resmi</label>
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input type="file" required name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
                            @Html.ValidationMessageFor(model => model.KategoriResim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>

            <div class="form-group">
                <div class="col-auto">
                    <a href="/AdminKategori/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-filter fe-12 mr-2"></span>Kaydet</button>
                </div>
            </div>

        </div>
    </div>
}
<div class="toast alert alert-danger" role="alert" id="mytost" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="mr-auto">Hata</strong>
    </div>
    <div class="toast-body">
        @TempData["kategorisonuc"]
    </div>
</div>

Views/AdminKategori/Delete.cshtml
@model on_e_commerce.Models.TblKategori



@{
    /**/

    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("Delete", "AdminKategori", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h3>" @Model.KategoriAdi " kategorisini silmek istiyor musun?</h3>
    <hr>
    <div class="alert alert-danger " role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        Lütfen kategoriyi silmeden önce kategoriye ait ürünleri silin !

    </div>


    <div class="card shadow">
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.KategoriId)
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                        @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4">Kategori Resmi</label>
                    <div class="col-md-8">
                        <div class="avatar avatar-md">
                            <img src="@Model.KategoriResim" alt="@Model.KategoriAdi" width="203" height="72">
                            @Html.ValidationMessageFor(model => model.KategoriResim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <a href="/AdminKategori/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-trash fe-12 mr-2"></span>Sil</button>
                </div>
            </div>
        </div>
    </div>
}
<div class="toast alert alert-danger" role="alert" id="mytost" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="mr-auto">Hata</strong>
    </div>
    <div class="toast-body">
        @TempData["kategorisonuc"]
    </div>
</div>

Views/AdminKategori/Details.cshtml
@model on_e_commerce.Models.TblKategori



@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Tbl_Kategori</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.KategoriAdi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KategoriAdi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsDelete)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsDelete)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.KategoriId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/AdminKategori/Edit.cshtml
@model on_e_commerce.Models.TblKategori

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using (Html.BeginForm("Edit", "AdminKategori", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <h4> " @Model.KategoriAdi " Kategorisini Düzenle</h4>
    <hr />
    <div class="card shadow">
        <div class="card-body">
            <div class="form-horizontal">
                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Adı</label>
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control", @required = "" } })
                        @Html.ValidationMessageFor(model => model.KategoriAdi, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-md-4">Mevcut Kategori Resmi</label>
                    <div class="col-md-8">
                        <div class="avatar avatar-md">
                            <img src="@Model.KategoriResim" alt="@Model.KategoriAdi" width="203" height="72">
                            @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-md-2">Kategori Resmi</label>
                    <div class="col-md-8">
                        <div class="custom-file">
                            <input type="file" name="gorsel" id="gorsel" accept=".jpg,.png,.jpeg,.gif" class="form-control" />
                            @Html.ValidationMessageFor(model => model.KategoriResim, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-4">
                    <a href="/AdminKategori/Index/"> <inp type="button" class="btn btn-danger"><span class="fe fe-chevron-left fe-12"></span>Geri Dön</a>
                    <button type="submit" class="btn btn-secondary"><span class="fe fe-edit-3 fe-12 mr-2"></span>Kaydet</button>
                </div>
            </div>
        </div>
    </div>
}
<div class="toast alert alert-danger" role="alert" id="mytost" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <strong class="mr-auto">Hata</strong>
    </div>
    <div class="toast-body">
        @TempData["kategorisonuc"]
    </div>
</div>


Views/AdminKategori/Index.cshtml
@model IEnumerable<on_e_commerce.Models.TblKategori>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Kategoriler</h2>

<p>
    <a href="/AdminKategori/Create/"> <inp type="button" class="btn mb-2 btn-outline-success"><span class="fe fe-filter fe-12 mr-2"></span>Kategori Oluştur</a>

</p>

<div class="card shadow">
    <div class="card-body">
        <div class="toolbar">
            <form class="form">
                <div class="form-row">
                    <div class="form-group col-auto mr-auto">
                        <label class="my-1 mr-2 sr-only" for="inlineFormCustomSelectPref1">Show</label>
                        <select class="custom-select mr-sm-2" id="inlineFormCustomSelectPref1">
                            <option value="">...</option>
                            <option value="1">12</option>
                            <option value="2" selected="">32</option>
                            <option value="3">64</option>
                            <option value="3">128</option>
                        </select>
                    </div>
                    <div class="form-group col-auto">
                        <label for="search" class="sr-only">Search</label>
                        <input type="text" class="form-control" id="search1" value="" placeholder="Search">
                    </div>
                </div>
            </form>
        </div>
        <table class="table table-borderless table-hover" id="dataTable-1">
            <thead>
                <tr>
                    <th></th>
                    <th>Kategori Resmi</th>
                    <th>Kategori Adı</th>
                    <th>Oluşturulma Tarihi</th>
                    <th>Değiştirilme Tarihi</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <div class="custom-control custom-checkbox">
                                <input type="checkbox" class="custom-control-input" id="@item.KategoriId">
                                <label class="custom-control-label" for="@item.KategoriId"></label>
                            </div>
                        </td>
                        <td>
                            <img src="@item.KategoriResim" alt="@item.KategoriAdi" width="203" height="72">
                        </td>
                        <td>
                            <p class="mb-0 text-muted"><strong>@Html.DisplayFor(modelItem => item.KategoriAdi)</strong></p>

                        </td>

                        <td>
                            <p class="mb-0 text-muted">@Html.DisplayNameFor(model => model.IsActive)</p>
                        </td>
                        <td>
                            <p class="mb-0 text-muted">@Html.DisplayNameFor(model => model.IsDelete)</p>
                        </td>
                        <td class="">
                            <button class="btn btn-sm dropdown-toggle more-horizontal" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="text-muted sr-only">Action</span>
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" >
                                <a class="dropdown-item " href="/AdminKategori/Edit/@item.KategoriId">Düzenle</a>
                                <a class="dropdown-item" href="/AdminKategori/Delete/@item.KategoriId">Sil</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <nav aria-label="Table Paging" class="mb-0 text-muted">
            <ul class="pagination justify-content-center mb-0">
                <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#">1</a></li>
                <li class="page-item active"><a class="page-link" href="#">2</a></li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
        </nav>
    </div>
</div>